#!/usr/bin/python 
import os,struct 
import sys
class LinuxProcess: #Created a class called "LinuxProcess" 
	def __init__(self,pid): 			
		self.file_name = "/proc/"+str(pid)+"/stat"
		f = open(self.file_name, "rb") 
		fp = f.read()
		word_list =fp.split() 
		self.pid = int(word_list[0]) 
		self.name = word_list[1]
		self.state = word_list[2]
		self.ppid = int(word_list[3]) 
		self.pgrp = int(word_list[4]) 
		self.session = int(word_list[5]) 
		self.tty_nr = int(word_list[6])
		self.tpgid = int(word_list[7]) 
		self.flags = int(word_list[8]) 
		self.minflt = int(word_list[9]) 
		self.cminflt = int(word_list[10]) 
		self.majflt = int(word_list[11]) 
		self.cmajflt = int(word_list[12])
		self.utime = int(word_list[13])
		self.stime = int(word_list[14]) 
		self.cutime = int(word_list[15]) 
		self.cstime = int(word_list[16]) 
		self.priority = int(word_list[17]) 
		self.nice = int(word_list[18])	
		self.num_threads = int(word_list[19])
		self.itrealvalue = int(word_list[20])
		self.starttime = int(word_list[21]) 
		self.vsize = int(word_list[22]) 
		self.rss = int(word_list[23]) 
		self.rss_lim = int(word_list[24]) 
		self.start_code = int(word_list[25]) 
		self.end_code = int(word_list[26]) 
		self.start_stack = int(word_list[27])
		self.esp = int(word_list[28])
		self.eip = int(word_list[29]) 
		self.signal = int(word_list[30]) 
		self.blocked = int(word_list[31]) 
		self.sigignore = int(word_list[32]) 
		self.sigcatch = int(word_list[33]) 
		self.wchan = int(word_list[34]) 
		self.nswap = int(word_list[35]) 
		self.cnswap = int(word_list[36])
		self.exit_signal = int(word_list[37]) 
		self.processor = int(word_list[38]) 
		self.rt_priority = int(word_list[39])
		self.policy = int(word_list[40]) 
		self.delayacct_blkio_ticks = int(word_list[41]) 
		self.guest_time = int(word_list[42]) 
		self.cguest_time = int(word_list[43]) 
		self.start_data = int(word_list[44]) 
		self.end_data = int(word_list[45]) 
		self.start_brk = int(word_list[46]) 
		self.arg_start = int(word_list[47]) 
		self.arg_end = int(word_list[48]) 
		self.env_start = int(word_list[49]) 
		self.env_end = int(word_list[50]) 
		self.exit_code = int(word_list[51]) 
		f.close()
	def print_proc(self):
		print "%20s" % "name: ", "%20s" % self.name
		print "%20s" % "rss_lim: ","%20s" % hex(self.rss_lim)  
		print "%20s" % "start_code: ","%20s" % hex(self.start_code)  
		print "%20s" % "end_code: ", "%20s" % hex(self.end_code)  
		print "%20s" % "start_stack: ","%20s" % hex(self.start_stack)
		print "%20s" % "esp: ","%20s" % hex(self.esp) 
		print "%20s" % "eip: ","%20s" % hex(self.eip) 
		print "%20s" % "start_data: ","%20s" % hex(self.start_data) 
		print "%20s" % "end_data: ","%20s" % hex(self.end_data)  
		print "%20s" % "start_brk: ","%20s" % hex(self.start_brk) 
		print "%20s" % "arg_start: ","%20s" % hex(self.arg_start) 
		print "%20s" % "arg_end: ","%20s" % hex(self.arg_end) 
		print "%20s" % "env_start: ","%20s" % hex(self.env_start) 
		print "%20s" % "env_end: ","%20s" % hex(self.env_end) 

#main 
proc = LinuxProcess(int(raw_input("Type pid: ")))  
proc.print_proc()
